version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - "npm install -g aws-cdk@1.70.0"
  build:
    commands:
      - "mkdir gen"
      - "mvn clean install -Dmaven.test.skip=true"
      # Synthesize application/service CDK stacks for application deployment
      - "mkdir gen/cloud-assembly"
      - "(cd application-infrastructure/ && cdk synth -o ../gen/cloud-assembly > /dev/null)"
      - "echo \"Generated $(cat gen/cloud-assembly/*.template.json | wc -l) template lines\""
  post_build:
    commands:
      - "echo \"Build completed at $(date)\""
artifacts:
  name: "cloud_assembly"
  base-directory: "gen/cloud-assembly"
  discard-paths: no
  files:
    - "**/*"
cache:
  paths:
    - '/root/.m2/**/*'
    - '/usr/local/lib/node_modules/aws-cdk/**/*'
