version: 0.2

phases:
  install:
    runtime-versions:
      runtime: corretto11
    commands:
      - "npm install -g aws-cdk"
  build:
    commands:
      - "mvn clean install"
      - "mkdir -p $CODEBUILD_SRC_DIR/relay-docker"
      # Copy relay artifacts to package as a Docker asset in CDK
      - "cp application-infrastructure/src/main/resource/RelayDockerfile relay-docker/Dockerfile"
      - "cp discord-relay/target/discord-relay.jar relay-docker/discord-relay.jar"
      # Synthesize CDK stacks using previous assets
      - "(cd deployment-infrastructure/ && cdk synth >/dev/null)"
      - "echo \"Generated $(cat deployment-infrastructure/target/cdk-assembly/*.template.json | wc -l) template lines\""
      - "(cd application-infrastructure && cdk synth >/dev/null)"
      - "echo \"Generated $(cat application-infrastructure/target/cdk-assembly/*.template.json | wc -l) template lines\""
  post_build:
    commands:
      - "echo \"Build completed at $(date)\""
artifacts:
  secondary-artifacts:
    # Looking like it won't be necessary to pass these: they are built into the CDK assemblies
    jar-files:
      files:
        - "app-daemon/target/*.jar"
        - "discord-relay/target/*.jar"
        - "command-lambda/target/*.jar"
        - "steps-lambda/target/*.jar"
        - "ip-lambda/target/*.jar"
      discard-paths: yes
    synth-deployment-infra:
      files:
        - "**/*"
      discard-paths: no
      base-directory: "deployment-infrastructure/target/cdk-assembly"
    synth-app-infra:
      files:
        - "**/*"
      discard-paths: no
      base-directory: "application-infrastructure/target/cdk-assembly"
