version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - "npm install -g aws-cdk"
  build:
    commands:
      - "mvn clean install"
      # Copy relay artifacts to package as a Docker asset in CDK
      - "mkdir -p $CODEBUILD_SRC_DIR/relay-docker"
      - "cp application-infrastructure/src/main/resources/RelayDockerfile relay-docker/Dockerfile"
      - "cp discord-relay/target/discord-relay.jar relay-docker/discord-relay.jar"
      # Synthesize deployment (i.e. pipeline) CDK stack for self-update
      - "(cd deployment-infrastructure/ && cdk synth >/dev/null)"
      - "echo \"Generated $(cat deployment-infrastructure/target/cdk-assembly/*.template.json | wc -l) template lines\""
      # Synthesize application/service CDK stacks for application deployment
      - "(cd application-infrastructure && cdk synth >/dev/null)"
      - "echo \"Generated $(cat application-infrastructure/target/cdk-assembly/*.template.json | wc -l) template lines\""
  post_build:
    commands:
      - "echo \"Build completed at $(date)\""
artifacts:
  secondary-artifacts:
    s3_jar_files:
      files:
        - "app-daemon/target/app-daemon.jar"
      discard-paths: yes
    cdk_assembly:
      files:
        - "**/*"
      discard-paths: no
      base-directory: "application-infrastructure/target/cdk-assembly"
