version: 0.2

env:
  shell: bash
  variables:
    CDK_VERSION: "1.130.0"
    GRAAL_RELEASE: "vm-22.0.0.2"
    GRAAL_ARTIFACT: "graalvm-ce-java17-linux-amd64-22.0.0.2"

    JAVA_HOME: "/usr/local/lib/graalvm/22.0.0.2"
    SOURCE_DATE_EPOCH: "1622959566" # Arbitrary: consistent with pom.xml epoch for sentimental reasons

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install NPM to 'global' local repo
      - "npm install -g aws-cdk@${CDK_VERSION}"
      # Download Graal only if not already installed (cached by version/GRAAL_RELEASE)
      - |
        if [[ -d "${JAVA_HOME}" ]]; then
          echo "GraalVM ${GRAAL_ARTIFACT} already installed"
        else
          mkdir -p "${JAVA_HOME}"
          GRAAL_DOWNLOAD="https://github.com/graalvm/graalvm-ce-builds/releases/download/"
          curl -Lo graal.tar.gz "${GRAAL_DOWNLOAD}/${GRAAL_RELEASE}/${GRAAL_ARTIFACT}.tar.gz"
          tar -xzf graal.tar.gz -C "${JAVA_HOME}" --strip 1 # Remove 'container' dir inside tarball
          ${JAVA_HOME}/bin/java -version
          ${JAVA_HOME}/bin/gu -v install native-image
        fi
  build:
    commands:
      # Add Java bin dir to path (not strictly required by mvn but handy for any other tools)
      - "export PATH=\"${JAVA_HOME}/bin:${PATH}\""
      # Compile Java modules
      - "mvn clean install -Dmaven.test.skip=true"
      # Prep python dependencies (CDK will zip up the asset automatically)
      # This is slightly hacked compared to regular `pip` to make it reproducible, which prevents unnecessary CF edge
      # Lambda deployments and saves significant deployment time.
      # -> SOURCE_DATE_EPOCH switches compilation to write source hashes instead of timestamps in .pyc files
      # -> tempfile monkeypatch seeds its RNG to use the same /tmp directory names, which end up in .pyc files too
      - |
        (
        cd web/url-shortener-frontend/edge-function && python3 <<EOF
        import pip, tempfile, random
        tempfile._Random = lambda: random.Random('fixed-seed-for-deterministic-pip-install')
        pip.main(['install', '-t', '.', '-r', 'requirements.txt'])
        EOF
        )
      # Synthesize application/service CDK stacks for application deployment
      - "mkdir -p gen/cloud-assembly"
      - "(cd deployment/application-infrastructure/ && cdk synth -o ../../gen/cloud-assembly)"
      - "echo \"Generated $(cat gen/cloud-assembly/*.template.json | wc -l) template lines\""
  post_build:
    commands:
      - "echo \"Build completed at $(date)\""
artifacts:
  name: "cloud_assembly"
  base-directory: "gen/cloud-assembly"
  discard-paths: no
  files:
    - "**/*"
cache:
  paths:
    - '/root/.m2/**/*'
    - '/usr/local/lib/node_modules/aws-cdk/**/*'
    - '/usr/local/lib/graalvm/**/*'
