version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - "npm install -g aws-cdk@1.111.0"
  build:
    commands:
      # Compile Java modules
      - "mvn clean install -Dmaven.test.skip=true"
      # Prep python dependencies (CDK will zip up the asset automatically)
      - "(cd web/url-shortener-frontend/edge-function && pip3 install -t . -r requirements.txt)"
      # Synthesize application/service CDK stacks for application deployment
      - "mkdir -p gen/cloud-assembly"
      - "(cd deployment/application-infrastructure/ && cdk synth -o ../../gen/cloud-assembly)"
      - "echo \"Generated $(cat gen/cloud-assembly/*.template.json | wc -l) template lines\""
  post_build:
    commands:
      - "echo \"Build completed at $(date)\""
artifacts:
  name: "cloud_assembly"
  base-directory: "gen/cloud-assembly"
  discard-paths: no
  files:
    - "**/*"
cache:
  paths:
    - '/root/.m2/**/*'
    - '/usr/local/lib/node_modules/aws-cdk/**/*'
